### ISSUE TITLE
Quick-understanding with CSS

### ISSUE THREAD

**Issue by PandaWood** [shagstrom/split-pane#33]
Can I just suggest you make it clear on how to use this - when it comes to CSS.
It seems like, given all your examples, you have to get the html/css all setup (maybe 100 lines) before you can use this.

But you've written that this is your "preference" and that is all.

Is it because it won't work any other way or you just prefer to create examples like this?

Then looking at the examples, I have to study carefully to figure out what CSS is in your own library and what I need to introduce.

**Comment by shagstrom** [comment]
Ah ok, I thought it was pretty clear.

The example in the readme file is 48 lines, including html boilerplate stuff. Some stuff would be necessary regardless. For example this, since the plugin doesn't know which size the website author wants on the parent container - body doesn't need to be the parent container.

    html, body {
        height: 100%;
        min-height: 100%;
        margin: 0;
        padding: 0;
    }

Using css is the only way to set up the split pane, so I might need to make that clearer in the readme.

**Comment by shagstrom** [comment]
Readme is updated. Thanks for your feedback!

**Comment by PandaWood** [comment]
Thanks. 
Sorry this is probably not the place, but on my first attempt, downloading the latest, I get
split-pane.js:125 Uncaught TypeError: internalHandler is not a function

**Comment by PandaWood** [comment]
I got past that - was putting the css classes in the wrong divs.
Still, even though I've specified a div as split-pane-divider having that class.
I don't see a divider after splitPane runs.
And if I insert HTML dynamically into that pane, it isn't confined to the pane, so basically doesn't work.
I'll try document all this, but I don't think I can use it
